# Generated by Django 3.0.8 on 2020-07-10 11:53

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20200710_0955'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='telephoneNumber',
            field=models.CharField(blank=True, max_length=14, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the valid format (for example: '+380999999999')", regex='^\\+?3?8?(0[5-9][0-9]\\d{7})$')]),
        ),
    ]
